# Generated by Django 3.1.6 on 2021-02-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=129)),
                ('inline', models.BooleanField()),
                ('content', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('to', models.TextField()),
                ('cc', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('text', models.TextField()),
                ('html', models.TextField()),
            ],
        ),
    ]
