# Generated by Django 3.1.6 on 2021-02-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="content",
            field=models.FileField(upload_to="attachments/"),
        ),
    ]
