# Generated by Django 3.1.6 on 2021-02-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0009_auto_20210213_1042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.IntegerField(choices=[(0, "Incoming"), (1, "Outgoing")]),
        ),
    ]
