# Generated by Django 3.1.6 on 2021-02-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0011_auto_20210213_1058"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="subject",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
