# Generated by Django 3.1.6 on 2021-02-13 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0012_thread_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thread",
            name="originally_from",
            field=models.CharField(default="", max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thread",
            name="recipient",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
