# Generated by Django 3.1.6 on 2021-03-13 23:12

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0016_auto_20210313_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='addresses',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, size=None),
        ),
    ]
