# Generated by Django 3.2 on 2021-05-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0017_auto_20210313_1512"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.IntegerField(
                choices=[
                    (None, "N/A"),
                    (0, "Pending"),
                    (1, "Delivered"),
                    (2, "Rejected"),
                    (3, "Bounced"),
                ],
                null=True,
            ),
        ),
    ]
