# Generated by Django 3.2 on 2021-05-05 17:02

from django.db import migrations, models
import django.db.models.deletion
import schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_name", models.CharField(max_length=255)),
                ("from_email", models.EmailField(max_length=254)),
                ("to", models.TextField()),
                ("subject", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("html", models.TextField()),
                ("send_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=129)),
                ("inline", models.BooleanField()),
                (
                    "content",
                    models.FileField(upload_to=schedule.models.upload_to_location),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.scheduledmessage",
                    ),
                ),
            ],
        ),
    ]
