# Generated by Django 3.2 on 2021-05-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledAttachment',
            new_name='Attachment',
        ),
        migrations.RenameModel(
            old_name='ScheduledMessage',
            new_name='Message',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['send_at']},
        ),
    ]
